quarkus:
  http:
    port: 8000
  vertx:
    prefer-native-transport: true
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=PHONECATALOG
    reactive:
      url: postgresql://localhost:5432/postgres
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    schemas: phonecatalog
    locations: db/migration

kafka:
  bootstrap:
    servers: localhost:9092
  messaging:
    outgoing:
      costumerorder:
        topic: test.costumerorders.topic
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
